### ISSUE TITLE
longid's Slice method should be named Bytes instead

### ISSUE THREAD

**Issue by nhooyr** [codercom/id#5]
It's more idiomatic and makes more sense.

**Comment by ammario** [comment]
It was for a while.. It's a little confusing because the long is already an alias of `[16]byte`

**Comment by nhooyr** [comment]
While that's true, it's convention in Go for the `Bytes()` method to return a slice of bytes representing the structure.

For example, see this package here https://godoc.org/github.com/satori/go.uuid#UUID.Bytes. The UUID is of type `[16]byte` but the method that returns the byte slice is named `Bytes`.

Or `bytes.Buffer.Bytes()` in the stdlib. I'm sure there are more examples too.
