### ISSUE TITLE
change shortid to be of type uint64

### ISSUE THREAD

**Issue by nhooyr** [codercom/id#6]
Since a shortid will never be negative, we might as well use that last bit.

**Comment by nhooyr** [comment]
Actually, it's interesting that io.Reader uses `int` and not `uint` for the bytes read value even though the bytes read can never be negative. Weird.

**Comment by ammario** [comment]
Unsigned bigints are not apart of the SQL standard (or popular databases like Postgres)

**Comment by nhooyr** [comment]
Ah, fair enough.
